/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.eduardo.abaddon;

@SuppressWarnings( "all" )
public final class R
{
   public static final class attr
   {
      /**
       * <p>
       * Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>" or to a
       * theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
       */
      public static final int buttonBarButtonStyle = 0x7f010001;

      /**
       * <p>
       * Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>" or to a
       * theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
       */
      public static final int buttonBarStyle = 0x7f010000;

      /**
       * <p>
       * Must be an integer value, such as "<code>100</code>".
       * <p>
       * This may also be a reference to a resource (in the form "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or theme
       * attribute (in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>") containing a value of this type.
       */
      public static final int spriteHeight = 0x7f010003;

      /**
       * <p>
       * Must be an integer value, such as "<code>100</code>".
       * <p>
       * This may also be a reference to a resource (in the form "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or theme
       * attribute (in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>") containing a value of this type.
       */
      public static final int tileSize = 0x7f010002;
   }

   public static final class color
   {
      public static final int black_overlay = 0x7f050000;
   }

   public static final class drawable
   {
      public static final int antiochinteriortiles = 0x7f020000;

      public static final int antiochtiles = 0x7f020001;

      public static final int cavetiles = 0x7f020002;

      public static final int ic_launcher = 0x7f020003;

      public static final int icon = 0x7f020004;

      public static final int newtiles = 0x7f020005;

      public static final int npc0 = 0x7f020006;

      public static final int npc1 = 0x7f020007;

      public static final int npc2 = 0x7f020008;

      public static final int npc3 = 0x7f020009;

      public static final int overworldtiles = 0x7f02000a;

      public static final int pathmarker = 0x7f02000b;

      public static final int pc3 = 0x7f02000c;

      public static final int window = 0x7f02000d;
   }

   public static final class id
   {
      public static final int abaddon = 0x7f080000;

      public static final int text = 0x7f080001;
   }

   public static final class layout
   {
      public static final int game_layout = 0x7f030000;
   }

   public static final class raw
   {
      public static final int antiochinterior = 0x7f040000;

      public static final int antiochinteriortiles = 0x7f040001;

      public static final int antiochtiles = 0x7f040002;

      public static final int antiochtown = 0x7f040003;

      public static final int cavetiles = 0x7f040004;

      public static final int fremenpassagecave = 0x7f040005;

      public static final int overworld = 0x7f040006;

      public static final int overworldtiles = 0x7f040007;

      public static final int pathfindercave = 0x7f040008;

      public static final int testinterior = 0x7f040009;
   }

   public static final class string
   {
      public static final int abaddon_text = 0x7f060006;

      public static final int app_name = 0x7f060000;

      public static final int mode_error = 0x7f060005;

      public static final int mode_loading = 0x7f060002;

      public static final int mode_lose = 0x7f060004;

      public static final int mode_pause = 0x7f060003;

      public static final int mode_ready = 0x7f060001;
   }

   public static final class style
   {
      /**
       * Base application theme, dependent on API level. This theme is replaced by AppBaseTheme from res/values-vXX/styles.xml on
       * newer devices.
       * 
       * 
       * 
       * Theme customizations available in newer API levels can go in res/values-vXX/styles.xml, while customizations related to
       * backward-compatibility can go here.
       * 
       * 
       * 
       * Base application theme for API 11+. This theme completely replaces AppBaseTheme from res/values/styles.xml on API 11+
       * devices.
       * 
       * 
       * API 11 theme customizations can go here.
       * 
       * Base application theme for API 14+. This theme completely replaces AppBaseTheme from BOTH res/values/styles.xml and
       * res/values-v11/styles.xml on API 14+ devices.
       * 
       * API 14 theme customizations can go here.
       */
      public static final int AppBaseTheme = 0x7f070000;

      /**
       * Application theme. All customizations that are NOT specific to a particular API-level can go here.
       */
      public static final int AppTheme = 0x7f070001;

      public static final int ButtonBar = 0x7f070003;

      public static final int ButtonBarButton = 0x7f070004;

      public static final int FullscreenActionBarStyle = 0x7f070005;

      public static final int FullscreenTheme = 0x7f070002;

      public static final int Theme_NoBackground = 0x7f070006;
   }

   public static final class styleable
   {
      /**
       * Declare custom theme attributes that allow changing which styles are used for button bars depending on the API level.
       * ?android:attr/buttonBarStyle is new as of API 11 so this is necessary to support previous API levels.
       * 
       * <p>
       * Includes the following attributes:
       * </p>
       * <table>
       * <colgroup align="left" /> <colgroup align="left" />
       * <tr>
       * <th>Attribute</th>
       * <th>Description</th>
       * </tr>
       * <tr>
       * <td><code>{@link #ButtonBarContainerTheme_buttonBarButtonStyle uk.co.eduardo.abaddon:buttonBarButtonStyle}</code></td>
       * <td></td>
       * </tr>
       * <tr>
       * <td><code>{@link #ButtonBarContainerTheme_buttonBarStyle uk.co.eduardo.abaddon:buttonBarStyle}</code></td>
       * <td></td>
       * </tr>
       * </table>
       * 
       * @see #ButtonBarContainerTheme_buttonBarButtonStyle
       * @see #ButtonBarContainerTheme_buttonBarStyle
       */
      public static final int[] ButtonBarContainerTheme =
      {
         0x7f010000,
         0x7f010001
      };

      /**
       * <p>
       * This symbol is the offset where the {@link uk.co.eduardo.abaddon.R.attr#buttonBarButtonStyle} attribute's value can be
       * found in the {@link #ButtonBarContainerTheme} array.
       * 
       * 
       * <p>
       * Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>" or to a
       * theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
       * 
       * @attr name android:buttonBarButtonStyle
       */
      public static final int ButtonBarContainerTheme_buttonBarButtonStyle = 1;

      /**
       * <p>
       * This symbol is the offset where the {@link uk.co.eduardo.abaddon.R.attr#buttonBarStyle} attribute's value can be found in
       * the {@link #ButtonBarContainerTheme} array.
       * 
       * 
       * <p>
       * Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>" or to a
       * theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
       * 
       * @attr name android:buttonBarStyle
       */
      public static final int ButtonBarContainerTheme_buttonBarStyle = 0;

      /**
       * Attributes that can be used with a MainView.
       * <p>
       * Includes the following attributes:
       * </p>
       * <table>
       * <colgroup align="left" /> <colgroup align="left" />
       * <tr>
       * <th>Attribute</th>
       * <th>Description</th>
       * </tr>
       * <tr>
       * <td><code>{@link #MainView_spriteHeight uk.co.eduardo.abaddon:spriteHeight}</code></td>
       * <td></td>
       * </tr>
       * <tr>
       * <td><code>{@link #MainView_tileSize uk.co.eduardo.abaddon:tileSize}</code></td>
       * <td></td>
       * </tr>
       * </table>
       * 
       * @see #MainView_spriteHeight
       * @see #MainView_tileSize
       */
      public static final int[] MainView =
      {
         0x7f010002,
         0x7f010003
      };

      /**
       * <p>
       * This symbol is the offset where the {@link uk.co.eduardo.abaddon.R.attr#spriteHeight} attribute's value can be found in the
       * {@link #MainView} array.
       * 
       * 
       * <p>
       * Must be an integer value, such as "<code>100</code>".
       * <p>
       * This may also be a reference to a resource (in the form "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or theme
       * attribute (in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>") containing a value of this type.
       * 
       * @attr name android:spriteHeight
       */
      public static final int MainView_spriteHeight = 1;

      /**
       * <p>
       * This symbol is the offset where the {@link uk.co.eduardo.abaddon.R.attr#tileSize} attribute's value can be found in the
       * {@link #MainView} array.
       * 
       * 
       * <p>
       * Must be an integer value, such as "<code>100</code>".
       * <p>
       * This may also be a reference to a resource (in the form "<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or theme
       * attribute (in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>") containing a value of this type.
       * 
       * @attr name android:tileSize
       */
      public static final int MainView_tileSize = 0;
   };
}
